### PR TITLE
Fix TKinter exceptions

### PR DESCRIPTION
**Pull request by Jeinzi**
I got a bunch of exceptions while using the GUI, for example
- TypeError: 'map' object is not subscriptable
- NameError: name 'tkFileDialog' is not defined
- NameError: name 'tkMessageBox' is not defined

With the changes in this commit I was again able to generate a results.txt. Would be glad if you could merge this, your fork seems like it is the official version for now :D

### CODE REVIEW

**Comment by mikhailmihalkov** [comment]
silhouette portrait 3 ?

**Comment by mikhailmihalkov** [comment]
Unfortunately with this script does not work silhouette portrait 3... The cutting part does not move, but the transfer of the phail goes

**Comment by mikhailmihalkov** [comment]
[log 1.txt](https://github.com/GatCode/SMTCut/files/8115114/log.1.txt)
[log 2  Portrait 3.txt](https://github.com/GatCode/SMTCut/files/8115116/log.2.Portrait.3.txt)

**Comment by mikhailmihalkov** [comment]
Jeinzi can you help with the launch of silhouette portrait 3?

**Comment by Jeinzi** [comment]
Sorry, I don't have any knowledge about the conversion process and I also don't have a Silhouette Portrait 3 for testing.

**Pull request closed without merging**
